version: "3"
services:
    mongo:
        image: mongo:6.0.9
        ports:
            - "27017:27017"

    mongo-express:
        image: mongo-express
        depends_on:
            - mongo
        ports:
            - "8081:8081"
